### ISSUE TITLE
Slug de identificação do conjunto de dados

### ISSUE THREAD

**Issue by silviana-faria** [dados-mg/remuneracao#1]
Escolhido `remuneracao-servidores-ativos` por votação (3x1).

**Comment by silviana-faria** [comment]
#### Prefeitura de São Paulo

[Histórico de Remuneração dos Servidores Ativos da Prefeitura de São Paulo](http://dados.prefeitura.sp.gov.br/pt_PT/dataset/remuneracao-servidores-prefeitura-de-sao-paulo)

**Comment by fjuniorr** [comment]
Resgatando a [discussão](https://trello.com/c/XBAt0SRO) sobre a escolha do slug de identificação, acho `remuneracao` muito amplo porque não responde remuneração de quem.

A prefeitura de São Paulo, exemplo da @silviana-faria, usa `remuneracao-servidores-prefeitura-de-sao-paulo` e o Portal da Transparência `estado-pessoal/remuneracao-dos-servidores`. Minha preferência é por inserir também a qualificação de ativos, ficando com `remuneracao-servidores-ativos` depois de retirar a preposição (não lembro onde combinamos isso).

Precisamos escolher uma slug hoje para responder o pedido [1520000062202067](https://github.com/transparencia-mg/pedidos-esic/blob/master/Respostas/1520_000062202067-remuneracao-anos-anteriores.md) então não vai ser possível deliberar de forma aprofundada.
