### ISSUE TITLE
Make retorna sh-4.4$ ao ser executado no git bash

### ISSUE THREAD

**Issue by fjuniorr** [dados-mg/remuneracao#25]
Ao tentar executar os targets do `make` dentro do projeto da remuneração no git bash o prompt retorna `sh-4.4$` e fica travado.

![AnyDesk](https://user-images.githubusercontent.com/4969445/104224559-e9eacd80-5423-11eb-8ce1-6c859853a186.png)

Ainda consigo executar um `make --version` normalmente.

No Prompt de Comando (cmd) o `make` funciona normalmente.

Não encontrei nada na internet relevante, mas esse erro parece ser geral tendo em vista essa [dúvida](https://stackoverflow.com/questions/54467896/sh-4-4-when-opening-vscode-terminal).

**Comment by carloshob** [comment]
Prezado @fjuniorr, 

Estávamos com o mesmo problema, tentamos várias alternativas e a que funcionou foi instalar concomitantemente as versões 32 e 64bits do Git. Pegamos as versões mais atualizadas do Git e demais aplicativos R e configuramos todos os ambientes com as definições-padrão de usuário sugeridas aqui: http://dcgf.gitlab.io/config-ambiente.html.

**Comment by fjuniorr** [comment]
De fato com as duas instalações funcionou @carloshob, obrigado!

Você chegou a testar somente com a versão 32 bits, independentemente da arquitetura do seu pc?
