### ISSUE TITLE
Source error - erro de validação goodtables

### ISSUE THREAD

**Issue by Andrelamor** [dados-mg/remuneracao#4]
Problema/referência job: https://goodtables.io/github/dados-mg/remuneracao/jobs/36

OBS.: esse erro apareceu após commit https://github.com/dados-mg/remuneracao/commit/e92e43b1188de44a03e23ef6ec73cdc5b9a08679 na tentativa de corrigir erro de validação relatado no issue #2 

Solução: a codificação dos arquivos estava como Western, bastou salvar com encoding UTF-8 + BOM no Sublime

**Comment by Andrelamor** [comment]
> Data reading error because of not supported or inconsistent contents.

> How it could be resolved:

>  Fix data contents (e.g. change JSON data to array or arrays/objects).
Set correct source settings in goodtables.yml.
The full list of error messages:

> 'utf-8' codec can't decode byte 0xaa in position 32: invalid start byte

![image](https://user-images.githubusercontent.com/52294411/98177837-3d97e280-1eda-11eb-8de4-700d87e2750e.png)

**Comment by fjuniorr** [comment]
@Andrelamor acho que o erro está indicando que esse arquivo não está codificado como UTF-8.
