### ISSUE TITLE
Letras minúsculas no nome dos recursos como padrão de especificação do goodtables

### ISSUE THREAD

**Issue by Andrelamor** [dados-mg/remuneracao#5]

**Comment by Andrelamor** [comment]
o [job 18](https://goodtables.io/github/dados-mg/remuneracao/jobs/18) tinha uma mensagem de warning

> Data Package "datapackage.json" has a validation error "Descriptor validation error: 'Servidores01_20' does not match '^([-a-z0-9./])+$' at "resources/0/name" in descriptor and at "properties/resources/items/properties/name/pattern" in profile"

Relendo a especificação de um datapackage, tem-se que:

> It MUST consist only of lowercase alphanumeric characters plus “.”, “-” and “_”.

Ou seja, o valor Servidores_01_20 é inválido porque tem um S maiúsculo.

**Comment by fjuniorr** [comment]
resolved 5c4735b50dd529301ba41c821555e8cc7b2b705e
